### ISSUE TITLE
Step 9  has incorrect command to check APIC version

### ISSUE THREAD

**Issue by fe01134** [ibm-cloud-architecture/refarch-omnichannel-api-node#3]
Steps to reproduce
Goto directions Installing the IBM API Connect Developer Toolkit
Type command apic -version
Gives error: Error: The command `-version` is invalid.

What works for me
apic -v
Gives "API Connect: v5.0.4.0-iFix2 (apiconnect: v2.3.10)"

Using IBM NodeJS v v6.7.0  on a mac.

**Comment by gangchen03** [comment]
thanks for catching the issue. The command has changed in apic cli. The pull request has been merged.
